- hosts: localhost
  connection: local
  become: true
 
  tasks:

  - include: tasks/cron-user.yml

  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim-nox
        - avahi-daemon
        - vim
