- name: add ansible user
  user:
    name: ansible-user
    system: yes
    shell: /bin/bash
 
- name: set up sudo for ansible user
  copy:
    src: files/sudoer_ansible-user
    dest: /etc/sudoers.d/ansible-user
    owner: root
    group: root
    mode: 0440
 
- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: ansible-user
    minute: "*/10"
    job: ansible-pull -o -U https://github.com/witenite/Cloud-Init-Ansible-Pull.git
